### ISSUE TITLE
Fails to run on windows

### ISSUE THREAD

**Issue by jkanche** [lanagarmire/deepimpute#10]
Hello,

DeepImpute fails to run properly on windows since it tries to save the model to `/tmp` which doesn't exist. 

https://github.com/lanagarmire/deepimpute/blob/027a33a97dbca401ccdceeabfea665943f082fb5/deepimpute/multinet.py#L87

my solution to get this running was to change the location to `os.getcwd()`. I thought this might help others running into the same issue!

Jay

**Comment by Puumanamana** [comment]
Hi Jay,

Thank you for reporting this issue. I pushed an update and it should use the correct temporary directory whatever OS you are using. 
Let me know if it did not work.

**Comment by jkanche** [comment]
thanks for updating!
