### ISSUE TITLE
The model cannot compiled 

### ISSUE THREAD

**Issue by Fanzwstatis** [lanagarmire/deepimpute#11]
I runed several files to impute my expression data, but When I run the model for one file, I got an error " The model can not be compiled because it has no loss to optimise.  I only have 92 gense in this file, so how do I modify the parameters? Thank you!

**Comment by Puumanamana** [comment]
Hi,
I have never tested DeepImpute on such a small number of genes, I'm not sure how it would perform. I would advise you to use more genes if you have them.
Regarding the error, I just fixed one bug. Try reinstalling the latest version. However, in order for it to work, you will need to have a smaller network. Try running it with --sub_outputdim 30 and --hidden-neurons 20

**Comment by Fanzwstatis** [comment]
Got it. I changed the outputdim into 31 and made it work, but  the performance of the method haven't verified yet. Thank you very much!
