### ISSUE TITLE
Unable to allocate 10.8 GiB for an array with shape (22675998, 128)

### ISSUE THREAD

**Issue by roxxaa** [lanagarmire/deepimpute#29]
![image](https://user-images.githubusercontent.com/96921698/149346087-9db549f0-3c66-400a-89c7-987a90fd62eb.png)

mini_kmeans_model = mini_kmeans(ipu.N_CLASSES * ipu.CLUSTER_FACTOR, np.array(all_train_dis))   

it is showing error for the particular code

**Comment by lanagarmire** [comment]
Hi, you would need to check how much RAM you have available. If you are failing at 10G request, then you likely need to upgrade to about 16G of RAM. You can also enable swap on your device which would allow more virtual memory available (but will be slower).
