### ISSUE TITLE
Usage on new dataset

### ISSUE THREAD

**Issue by aanchalMongia** [lanagarmire/deepimpute#3]
To use deepimpute on a new data set, can you please specify how to processes it before calling the deepImpute() function? The paper mentions that data is log transformed but lacks details on the pseudo count and base of logarithmic function.

**Comment by Puumanamana** [comment]
Hi,
Actually, the preprocessing is included in the pipeline, you just need to provide the raw count and run the deepImpute function directly.
But to answer your question, we use the natural logarithm (base e).

**Comment by aanchalMongia** [comment]
Thanks!
