### ISSUE TITLE
Getting an error after training

### ISSUE THREAD

**Issue by LouisFaure** [lanagarmire/deepimpute#5]
Hi, thanks for this package, I am really looking forward to apply this on my dataset, sadly I am getting an error after training:

---- Hyperparameters summary ----
Layer-0 ['label: dense', 'activation: relu', 'nb_neurons: 128']
Layer-1 ['label: dropout', 'activation: dropout', 'rate: 0.2']
Layer-2 ['label: dense', 'activation: softplus']
Batch size 64
Learning rate 0.0001
Loss function <function wMSE at 0x7f5c28dff9d8>
Traceback (most recent call last):
  File "DeepImpute.py", line 8, in <module>
    imputed = deepImpute(data, NN_lim='auto', n_cores=16, cell_subset=1)
  File "/home/lfaure/anaconda3/lib/python3.6/site-packages/deepimpute/deepImpute.py", line 18, in deepImpute
    return multi.predict(data, imputed_only=imputed_only,restore_pos_values=restore_pos_values)
TypeError: predict() got an unexpected keyword argument 'restore_pos_values'

Any idea of what could be the problem?

Best Wishes,

Louis Faure

**Comment by Puumanamana** [comment]
Hi Louis,

Thanks for reporting the error. I found the bug and it should work just fine now.
Let me know if the problem persist of if you get any more errors.

Best,
Cédric

**Comment by LouisFaure** [comment]
Hi Cédric,

Thanks a lot for the fast fix and answer! Error is fixed now. I am closing the issue.

BW,

Louis
