### ISSUE TITLE
Input and Output

### ISSUE THREAD

**Issue by Winnie09** [lanagarmire/deepimpute#6]
Dear author,

Thanks for developing the software! I have a few questions but did not find clear answer from your paper:

1. is the input a count matrix?
2. is the output a count matrix? Has it been normalized by library size, or log2-transformed?

Thanks!

**Comment by Puumanamana** [comment]
Sorry for the delay.
If you're still wondering, you only need the raw count matrix. No normalization is needed.

**Comment by Winnie09** [comment]
Thanks for the reply! But it says on the page 6 line 13-15 of Deepimpute bioRxiv manuscript that "We preprocess the datasets according to each method’s standard: using log transformation for dataset in MAGIC and DeepImpute, but raw counts for scImpute, DrImpute and SAVER." ?

**Comment by Puumanamana** [comment]
Yes, you're right. 
But the log transformation is already included in the method itself, no need to do it yourself.

**Comment by Winnie09** [comment]
The output matrix of DeepImpute contains values larger than 200, if the input is raw count matrix. Can you confirm that log-transform is included in the method itself? Thanks.

**Comment by Puumanamana** [comment]
DeepImpute takes care of the log transformation and to undo it in the end. So yes, log-tranformation is included in the method itself.
