### ISSUE TITLE
unexpected keyword argument 

### ISSUE THREAD

**Issue by Winnie09** [lanagarmire/deepimpute#8]
Hi, 
I have the following error when running deepimpute:

```
Traceback (most recent call last):
  File "deepImpute.py", line 117, in <module>
    NN_params=NN_params
  File "deepImpute.py", line 12, in deepImpute
    multi = MultiNet(**NN_params)
TypeError: __init__() got an unexpected keyword argument 'NN_params'

```

**Comment by Puumanamana** [comment]
Hi,

How did you run DeepImpute? What command did you use?

**Comment by Winnie09** [comment]
I use the following commands under cuda/9.0 and python/3.6.

`python deepimpute/deepImpute.py cellbygene.csv result.csv`

**Comment by Puumanamana** [comment]
Thank you for reporting this error.
I was able to fix it and it should work now. Let me know if the problem persists.
Also, make sure when you use the command line to use '-o' options for the output file, it won't work otherwise:
`python deepimpute/deepImpute.py cellbygene.csv -o result.csv`

**Comment by Winnie09** [comment]
Thanks for the reply. I reinstall deepimpute and use your code, but get another error:

```
Traceback (most recent call last):
  File "deepimpute/deepImpute.py", line 117, in <module>
    **NN_params
  File "deepimpute/deepImpute.py", line 14, in deepImpute
    return multi.predict(data, imputed_only=imputed_only, policy=policy)
  File "deepimpute_venv/lib/python3.6/site-packages/deepimpute/multinet.py", line 250, in predict
    imputed[mask] = raw.values[mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3496 but corresponding boolean dimension is 266
```

**Comment by Puumanamana** [comment]
I can't reproduce your error. Does it work with the test data in `deepimpute/examples/test.csv`?
`python deepimpute/deepImpute.py  deepimpute/examples/test.csv -o result.csv`

If it works, then the issue probably comes from the dataset itself. Could you share it with me? (or at least part of it).

**Comment by Winnie09** [comment]
[cellbygene.csv.zip.gz](https://github.com/lanagarmire/deepimpute/files/3424151/cellbygene.csv.zip.gz)

**Comment by Puumanamana** [comment]
Thank you. After looking at it, it seems your dataset has duplicated cells labels. It worked for me once I used unique names. I have changed the code to add a more helpful error message.
Let me know if you run into any other issues.

**Comment by Winnie09** [comment]
Thanks! That is very helpful.
