### ISSUE TITLE
input was not read as its appropriate dimension

### ISSUE THREAD

**Issue by Winnie09** [lanagarmire/deepimpute#9]
Hi,

I am running Deepimpute to impute a normalized scRNA-seq data of dimension 1000(cells) by 7312(genes). I got this error:

    "Shape of passed values is {0}, indices imply {1}".format(passed, implied)
ValueError: Shape of passed values is (512000, 1), indices imply (1000, 512)

Do you know what might be the cause of it? Thanks!

**Comment by Puumanamana** [comment]
Hi Winnie,
Do you have the full traceback?
Also, DeepImpute was tested with raw count, I can't guarantee the result for normalized data. Do you know what normalization procedure was performed?

**Comment by Winnie09** [comment]
Sorry for the late response. I have run deepimpute on a different dataset and has the same problem. See below for the full output.

Using TensorFlow backend.
Using all the cores (24)
Input dataset is 59620 cells (rows) and 1812 genes (columns)
First 3 rows and columns:
                          ISG15  SDF4  AURKAIP1
b_cells:AAACATACAATGCC-1      0     0         1
b_cells:AAACATACACGCAT-1      0     0         0
b_cells:AAACATACGAATAG-1      1     0         0
512 genes selected for imputation
Net 0: 161 predictors, 512 targets
Normalization
WARNING: Logging before flag parsing goes to stderr.
W0924 08:34:31.432043 47981409759104 deprecation_wrapper.py:119] From /home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/deepimpute/multinet.py:200: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

W0924 08:34:31.453669 47981409759104 deprecation_wrapper.py:119] From /home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/deepimpute/multinet.py:202: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0924 08:34:31.454352 47981409759104 deprecation_wrapper.py:119] From /home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/deepimpute/multinet.py:206: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Building network
[{'type': 'dense', 'activation': 'relu', 'neurons': 300}, {'type': 'dropout', 'activation': 'dropout', 'rate': 0.2}]
W0924 08:34:31.461900 47981409759104 deprecation_wrapper.py:119] From /home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0924 08:34:31.462113 47981409759104 deprecation_wrapper.py:119] From /home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0924 08:34:31.488047 47981409759104 deprecation.py:506] From /home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Fitting with 59620 cells
Train on 56639 samples, validate on 2981 samples
Epoch 1/300
56639/56639 [==============================] - 3s 50us/step - loss: 0.2122 - val_loss: 0.1137
Epoch 2/300
56639/56639 [==============================] - 3s 46us/step - loss: 0.1200 - val_loss: 0.1090
Epoch 3/300
56639/56639 [==============================] - 3s 48us/step - loss: 0.1144 - val_loss: 0.1069
Epoch 4/300
56639/56639 [==============================] - 3s 48us/step - loss: 0.1113 - val_loss: 0.1053
Epoch 5/300
56639/56639 [==============================] - 3s 50us/step - loss: 0.1093 - val_loss: 0.1046
Epoch 6/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1082 - val_loss: 0.1060
Epoch 7/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1069 - val_loss: 0.1034
Epoch 8/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1064 - val_loss: 0.1032
Epoch 9/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1058 - val_loss: 0.1031
Epoch 10/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1053 - val_loss: 0.1032
Epoch 11/300
56639/56639 [==============================] - 3s 46us/step - loss: 0.1046 - val_loss: 0.1031
Epoch 12/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1044 - val_loss: 0.1032
Epoch 13/300
56639/56639 [==============================] - 3s 48us/step - loss: 0.1039 - val_loss: 0.1023
Epoch 14/300
56639/56639 [==============================] - 3s 48us/step - loss: 0.1037 - val_loss: 0.1025
Epoch 15/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1033 - val_loss: 0.1020
Epoch 16/300
56639/56639 [==============================] - 3s 46us/step - loss: 0.1031 - val_loss: 0.1021
Epoch 17/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1029 - val_loss: 0.1016
Epoch 18/300
56639/56639 [==============================] - 3s 46us/step - loss: 0.1026 - val_loss: 0.1021
Epoch 19/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1023 - val_loss: 0.1036
Epoch 20/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1021 - val_loss: 0.1016
Epoch 21/300
56639/56639 [==============================] - 3s 45us/step - loss: 0.1018 - val_loss: 0.1017
Epoch 22/300
56639/56639 [==============================] - 3s 45us/step - loss: 0.1018 - val_loss: 0.1014
Epoch 23/300
56639/56639 [==============================] - 3s 53us/step - loss: 0.1015 - val_loss: 0.1020
Epoch 24/300
56639/56639 [==============================] - 3s 52us/step - loss: 0.1015 - val_loss: 0.1018
Epoch 25/300
56639/56639 [==============================] - 3s 46us/step - loss: 0.1013 - val_loss: 0.1019
Epoch 26/300
56639/56639 [==============================] - 3s 45us/step - loss: 0.1012 - val_loss: 0.1028
Epoch 27/300
56639/56639 [==============================] - 3s 44us/step - loss: 0.1010 - val_loss: 0.1013
Epoch 28/300
56639/56639 [==============================] - 3s 45us/step - loss: 0.1008 - val_loss: 0.1014
Epoch 29/300
56639/56639 [==============================] - 3s 49us/step - loss: 0.1005 - val_loss: 0.1016
Epoch 30/300
56639/56639 [==============================] - 3s 49us/step - loss: 0.1006 - val_loss: 0.1022
Epoch 31/300
56639/56639 [==============================] - 3s 46us/step - loss: 0.1003 - val_loss: 0.1012
Epoch 32/300
56639/56639 [==============================] - 3s 45us/step - loss: 0.1001 - val_loss: 0.1013
Epoch 33/300
56639/56639 [==============================] - 3s 45us/step - loss: 0.1001 - val_loss: 0.1017
Epoch 34/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.1000 - val_loss: 0.1017
Epoch 35/300
56639/56639 [==============================] - 3s 47us/step - loss: 0.0998 - val_loss: 0.1016
Epoch 36/300
56639/56639 [==============================] - 3s 46us/step - loss: 0.0998 - val_loss: 0.1013
Stopped fitting after 36 epochs
Saved model to disk
Traceback (most recent call last):
  File "/home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1677, in create_block_manager_from_blocks
    make_block(values=blocks[0], placement=slice(0, len(axes[0])))
  File "/home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 3265, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 128, in __init__
    "{mgr}".format(val=len(self.values), mgr=len(self.mgr_locs))
ValueError: Wrong number of items passed 1, placement implies 512

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home-4/whou10@jhu.edu/deepimpute/deepimpute/deepImpute.py", line 117, in <module>
    **NN_params
  File "/home-4/whou10@jhu.edu/deepimpute/deepimpute/deepImpute.py", line 14, in deepImpute
    return multi.predict(data, imputed_only=imputed_only, policy=policy)
  File "/home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/deepimpute/multinet.py", line 258, in predict
    columns=self.targets.flatten())
  File "/home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/pandas/core/frame.py", line 439, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 213, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1687, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/home-net/home-4/whou10@jhu.edu/deepimpute_venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1718, in construction_error
    "Shape of passed values is {0}, indices imply {1}".format(passed, implied)
ValueError: Shape of passed values is (30525440, 1), indices imply (59620, 512)

**Comment by Puumanamana** [comment]
Hi Winnie,
Thank you for your feedback. I fixed the issue, you can download the latest update. 
Let me know if it works.
